#!/bin/bash
set -euo pipefail
IFS=$'\n\t'



# from https://rizvir.com/articles/two-factor-auth-android-backup/
# generic cmd
# adb backup -f freeotp.bak org.fedorahosted.freeotp


# FIXME should we put this somewhere safer?
unencrypted_file=$(mktemp /tmp/freeotp.bak.XXX)
encrypted_file="$HOME/Documents/secrets/freeotp.bak.gpg..pass=abc"

echo "==> Backing up"
echo " ->  Use 'abc' as the password on android prompt, I'll encrypt the backup anyway..."
adb backup -f "$unencrypted_file" org.fedorahosted.freeotp

echo "==> Encrypting"
function clean_up {
  set -euo
  echo "==> Cleaning up!"
  rm "$unencrypted_file"
}
gpg --encrypt --recipient "vise890@visint.in" --output "$encrypted_file" "$unencrypted_file" || clean up
clean_up
