#!/bin/python
"""Prints a random, quick cleaning chore"""

import random
import os

SCRIPT_PATH = os.path.realpath(__file__)
SCRIPT_DIR = os.path.dirname(SCRIPT_PATH)
CLEANING_TXT_PATH = os.path.join(SCRIPT_DIR, "cleaning.txt")

with open(CLEANING_TXT_PATH, 'r') as cf:
    CHORES = [c.strip() for c in cf.readlines()]

print("==> Hooray! time to clean! Today you get toooo:\n")
print(random.choice(CHORES))
print()
