#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

cwd=$(pwd)

compiled_blog_path="$CODEPATH/vise890.github.io"
blog_path="$ORGPATH/blog"

cd "$compiled_blog_path"

echo "==> compiling _pages"
harp compile "$blog_path" ./

echo "==> committing all changes"
git add .
git commit -m "update blog"

echo "==> pushing all changes"
git push

cd "$cwd"
