#!/usr/bin/env ruby

require './variables.rb'

BLOG_PATH = "#{ORG_PATH}/blog/"

POST_TITLE = ARGV.join("_").downcase
if POST_TITLE.empty?
  puts("Must specify a blog title!")
  exit 1
end

post_filename = "#{Time.now.strftime("%Y%m%d")}-#{POST_TITLE}.md"
post_path = BLOG_PATH + post_filename

system "#{EDITOR} #{post_path}"
