#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sudo -v

# to debug:
# uname -a; lspci -nnk | grep -iA2 net; lsusb; dmesg | grep -i bluetooth; dmesg | grep -i firmware; lsmod | grep bluetooth
#  --> make sure firmware is loaded
# follow:
# https://wiki.archlinux.org/index.php/Bluetooth_headset#Connecting_works.2C_but_I_cannot_play_sound


echo '==> install firmware + symlink to right name'
pacaur -S bcm20703a1-firmware
sudo ln -s BCM20703A1-0a5c-6410.hcd BCM-0a5c-6410.hcd

echo '==> disallow starting pulseaudio in gdm'
# https://wiki.archlinux.org/index.php/Bluetooth_headset#Connecting_works.2C_but_I_cannot_play_sound
sudo mkdir -p ~gdm/.config/systemd/user
sudo ln -s /dev/null ~gdm/.config/systemd/user/pulseaudio.socket
