#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

echo "-> xdpyinfo (x11)"
xdpyinfo | grep -B 2 resolution

echo "-> xrdb"
xrdb -query | grep dpi

font="Ubuntu Mono:size=12"
echo "-> rendering $font"
xfd -fa "$font"
