#!/usr/bin/env ruby

require 'securerandom'

require 'clipboard'

pass = `pwgen -1 --ambiguous --capitalize --numerals --secure --symbols 15`

puts pass

Clipboard.copy pass
puts "==> Password copied to clipboard"
