#!/bin/bash
# Call this script with one parameter
# sh git_update_submodule foo
set -euo pipefail
IFS=$'\n\t'

SUBMODULE_PATH=$1

echo "==> fetching submodule and merging with origin/master"
(cd "$SUBMODULE_PATH"
  git fetch
  git merge origin/master
)

echo "==> staging changes to submodule"
git add "$SUBMODULE_PATH"
