#!/bin/bash

git branch -r --merged | grep -v master | sed 's/origin\///' | xargs -n 1 git push --delete origin
git remote prune origin
git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d
