#!/bin/bash

echo '==> deleting local merged branches'
git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d

echo '==> delete branches that no longer exist on `origin`'
git remote prune origin

echo '==> delete merged brances on `origin`'
git branch -r --merged | grep -v master | sed 's/origin\///' | xargs -n 1 git push --delete origin
