#!/bin/env ruby

gitignores = `find ./ -type f -iname '.gitignore'`.split("\n").map(&:chomp)

# yeeeeha!
class String
  def blank?
    self !~ /[^[:space:]]/
  end

  def comment?
    self.start_with?('#')
  end
end

gitignored_files = gitignores.map do |gitignore_path|
  gitignore_dir = File.dirname(gitignore_path)
  gitignored_files_basenames =
    File.readlines(gitignore_path)
      .reject { |l| l.blank? || l.comment? }
  gitignored_files_basenames
    .map { |basename| File.join(gitignore_dir, basename) }
end

puts gitignored_files
