#!/usr/bin/env ruby

require_relative './variables.rb'

JOURNAL_PATH = "#{ORG_PATH}/journal/"

todays_journal_title = "#{Time.now.strftime("%Y%m%d")}.md"

todays_journal_path = JOURNAL_PATH + todays_journal_title

system "#{EDITOR} #{todays_journal_path}"
