#!/bin/bash
set -euo pipefail
IFS=$' \n\t'

echo "==> getting namespace"
namespaces=$(kubectl get namespaces --output jsonpath="{.items[*]['metadata.name']}"; echo)

for namespace in $namespaces; do
  mkdir -p "$namespace" # sod it

  echo "==> getting secrets for namespace $namespace"
  secrets=$(kubectl get secrets --namespace="$namespace" --output jsonpath="{.items[*]['metadata.name']}"; echo)
  for secret in $secrets; do
    s_export_path="$namespace/$secret.yaml"
    echo "==> saving secret $secret in $s_export_path"
    kubectl get secret "$secret" --namespace "$namespace" --export --output yaml > "$s_export_path"
  done
done

