#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

gpg --decrypt ~/.lein/credentials.clj.gpg > ~/.lein/credentials.clj

$EDITOR ~/.lein/credentials.clj

gpg --default-recipient-self -e ~/.lein/credentials.clj > ~/.lein/credentials.clj.gpg
rm ~/.lein/credentials.clj
