#!/bin/bash
set -uo pipefail
IFS=$'\n\t'

# NOTE: can't put it all in the `do` or it won't run them
#       all if something fails
lein do clean, check
lein with-profile lint kibit
lein with-profile lint eastwood
lein with-profile lint bikeshed -v
lein with-profile lint yagni -v

