#!/bin/bash
set -euo pipefail
IFS=$'\n\t'


function new_script () {
  local script_path="$1"

  cat >> "$script_path" <<EOF
#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

EOF
  chmod +x "$script_path"
}

script_name=$1
script_path="$CODEPATH/scripts/$script_name"
if [ ! -e "$script_path" ]
then
  new_script "$script_path"
fi

"$EDITOR" "$script_path"
