#!/usr/bin/env python
import os
import glob

echo "==> converting all .txt to .md"
for filename in glob.glob("*.txt"):
    basename = os.path.splitext(filename)[0]
    new_name = basename + ".md"
    os.rename(filename, new_name)

echo "==> converting all filenames to lowercase"
for filename in os.listdir(os.curdir):
    # TODO: exclude [".git", "README.md"]
    os.rename(filename, filename.lower())
