#!/usr/bin/env python

import sys
from subprocess import call

def make_set(output):
    return set(output.split("\n"))

pkgs = make_set(sys.stdin.read())

cmd = ["sudo", "pacman", "-D", "--asdeps"]
cmd.extend(pkgs)

print("==> Marking packages as dependencies")
call(cmd)
