#!/usr/bin/env python

"""
List the explicitly installed pkgs that are not in base nor base-devel
"""


from pacman import my_explicits


EXPL = list(my_explicits())
EXPL.sort()


print("\n".join(EXPL))
