#!/usr/bin/env python

# Lists the exlicti

from utils import make_set

essentials = make_set("pacman -Qq --groups base base-devel")
explicits = make_set("pacman -Qq --explicit")
non_base_explicits = explicits.difference(essentials)

print("\n".join(non_base_explicits))
