#!/usr/bin/env python
from subprocess import getoutput
import os
import sys

def get_broken_packages():

    def pkg_name(pkg_line):
        return pkg_line.split(":")[0]

    cmd = " | ".join([
        "sudo pacman -Q --check 2> /dev/null",
        "ag --invert-match '0 missing files$'"
    ])

    out = getoutput(cmd)

    return [pkg_name(pkg_line) for pkg_line in out.split("\n") if pkg_name(pkg_line) != '']


broken_packages = get_broken_packages()


if not broken_packages:
    sys.exit()


print("==> found broken packages:\n", broken_packages)


print("==> Nuking them:\n")
os.system("sudo pacman -Rdd --noconfirm " + " ".join(broken_packages))


print("==> Re-installing:\n")
os.system("sudo pacman -S --noconfirm " + " ".join(broken_packages))

