#!/bin/bash
set -euo pipefail
IFS=$'\n\t'


my_explicits=$(pacman_my_explicits | sort -u)
pkgs_files_in_cwd=$(find ./ -type f -iname '*.pkgs')

pkgs=$(echo "$pkgs_files_in_cwd" | xargs cat| tr ' ' '\n' | sort -u)

comm -3 <(echo "$pkgs") <(echo "$my_explicits")

