#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

my_explicits=$(pacman_my_explicits | sort -u)
pkgs=$("$DIR/pkgs_in_cwd")

comm -3 <(echo "$pkgs") <(echo "$my_explicits")

