#!/usr/bin/env ruby

require 'uri'

def extract_domain(url)
  url = "http://#{url}" if URI.parse(url).scheme.nil?
  host = URI.parse(url).host.downcase
  host.start_with?('www.') ? host[4..-1] : host
end

def get_url(url)
  `wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=windows \
     --domains #{extract_domain(url)} \
     --no-parent \
     #{url}`
end

URL = ARGV[0]
if URL
  get_url(URL)
else
  puts("Usage: scrape wwww.foo.com/bar/baz")
end
