#!/bin/ruby

# Usage split_dir ./path/to/split
#
# will split the dir into ./partitions/0-N dirs of 50,000 files each

require 'pathname'

dir_to_split = Pathname.new(ARGV[0])
n_files = ARGV[1].to_i || 50_000

files = Dir.entries(dir_to_split).map{ |p| dir_to_split.join(p).realpath }

`mkdir -p partitions`

idx = 0
files.each_slice(n_files) { |fs|
  partition_dir = "./partitions/#{idx}"
  idx += 1
  Dir.mkdir(partition_dir)
  fs.each_slice(1_000) { |cfs|
    file_paths = cfs.join(" ")
    `cp --target-directory="#{partition_dir}" #{file_paths}`
  }
}
