#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

export GIT_COMMITTER_NAME="RoBotron-2000"
export GIT_COMMITTER_EMAIL="RoBotron-2000@cron.org"

export GIT_AUTHOR_NAME="RoBotron-2000"
export GIT_AUTHOR_EMAIL="RoBotron-2000@cron.org"

(
  cd "$HOME/org" || exit

  git pull || true
  git push origin master || true

  git add .
  git commit -m 'sync'
  git push origin master
)
