#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

user=$(whoami)
hostname=$(cat /etc/hostname)

export GIT_COMMITTER_NAME=$user
export GIT_COMMITTER_EMAIL="$user@$hostname"

export GIT_AUTHOR_NAME=$user
export GIT_AUTHOR_EMAIL="$user@$hostname"

(
  cd "$HOME/org" || exit

  git pull || true
  git push origin master || true

  git add .
  git commit -m 'sync'
  git push origin master
)
