#!/bin/bash
set -uo pipefail
IFS=$'\n\t'

sudo -v

echo "==> full sys upgrade (pacman)"
sudo pacman -Syu --noconfirm

echo "==> full AUR upgrade (pacaur)"
pacaur -Syu --noedit --noconfirm

echo "==> stack update"
stack update
echo "==> npm update"
npm install --global npm
npm update --global

echo "==> pip (python) update"
LOCATION="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
"$LOCATION/pip_upgrade.sh"

echo "==> update tldr docs"
tldr --update

export ZSH=$HOME/.oh-my-zsh

#echo "==> update oh-my-zsh"
#upgrade_oh_ms_zsh

#echo "==> update scm breeze"
#source "$HOME/.scm_breeze/scm_breeze.sh"
#update_scm_breeze

echo "==> DONE"
echo "==> now *you* merge '.pacnew's"
sudo etc-update


